package com.naulian.composer

object IElementType {
    const val HEADER = "header"
    const val BLOCK_SYMBOL = "block_symbol"
    const val COLOR_START = "color_start"
    const val COLOR_END = "color_end"
    const val COLOR_HEX = "color_hex"
    const val ELEMENT_BULLET = "element_bullet"
    const val ELEMENT_UNCHECKED = "element_unchecked"
    const val ELEMENT_CHECKED = "element_checked"
    const val ELEMENT = "element"
    const val TABLE_END = "table_end"
    const val TABLE_START = "table_start"
    const val PIPE = "pipe"
    const val TABLE = "table"
    const val TABLE_COLOMN = "table_column"
    const val BOLD = "bold"
    const val ITALIC = "italic"
    const val UNDERLINE = "underline"
    const val STRIKE = "strike"
    const val TEXT = "text"
    const val PARAGRAPH = "paragraph"
    const val IMAGE = "image"
    const val VIDEO = "video"
    const val YOUTUBE = "youtube"
    const val LINK = "link"
    const val HYPER_LINK = "hyper_link"
    const val WHITESPACE = "whitespace"
    const val NEWLINE = "newline"
    const val QUOTATION = "quotation"
    const val CODE = "code"
    const val DATETIME = "datetime"
    const val ESCAPE = "escape"
    const val IGNORE = "ignore"
    const val COLORED = "colored"
    const val DIVIDER = "divider"
    const val EOF = "eof"
    const val ROOT = "root"
    const val H1 = "h1"
    const val H2 = "h2"
    const val H3 = "h3"
    const val H4 = "h4"
    const val H5 = "h5"
    const val H6 = "h6"
}