package composer.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import composer.res.Res
import org.jetbrains.compose.resources.ExperimentalResourceApi

/**
 * The full **Google Material Symbols Rounded** set (Apache 2.0), bundled for internal
 * editor UI. Rather than ~3,900 separate resource files, all icons live in one compact
 * asset (`composeResources/files/material_symbols.txt`, `name⇥f|0|pathData⇥…` per line,
 * generated by `gen_symbols.py` from `@material-symbols/svg-400`'s `rounded/` SVGs). The
 * asset is loaded once on first use; each requested icon is parsed into a Compose
 * [ImageVector] on demand (via [PathParser]) and cached.
 *
 * Material Symbols use a `0 -960 960 960` viewBox (Y runs negative), so the builder uses
 * a 960 viewport with a translateY(960) group to bring the art into positive space.
 *
 * Use [SymbolIcon] to render any icon by its Material Symbols name (e.g. `"home"`).
 */
object Symbols {
    /** Flips true once the asset is parsed; snapshot state so [SymbolIcon]s recompose. */
    var loaded by mutableStateOf(false)
        private set

    private var started = false
    private val entries = HashMap<String, String>() // name -> "f|0|d\tf|0|d..."
    private val cache = HashMap<String, ImageVector?>()
    private var sortedNames: List<String> = emptyList()

    /** All icon names, sorted. Empty until [load] completes. */
    val names: List<String> get() = sortedNames

    @OptIn(ExperimentalResourceApi::class)
    suspend fun load() {
        if (started) return
        started = true
        val text = Res.readBytes("files/material_symbols.txt").decodeToString()
        for (line in text.splitToSequence('\n')) {
            val tab = line.indexOf('\t')
            if (tab <= 0) continue
            entries[line.substring(0, tab)] = line.substring(tab + 1)
        }
        sortedNames = entries.keys.sorted()
        loaded = true
    }

    /** The [ImageVector] for [name], built + cached on first request. Null if unknown. */
    fun vector(name: String): ImageVector? = cache.getOrPut(name) {
        val fields = entries[name] ?: return@getOrPut null
        val b = ImageVector.Builder(
            defaultWidth = 24.dp, defaultHeight = 24.dp,
            viewportWidth = 960f, viewportHeight = 960f,
        )
        b.addGroup(translationY = 960f)
        for (part in fields.split('\t')) {
            val seg = part.split('|', limit = 3)
            if (seg.size < 3) continue
            b.addPath(
                PathParser().parsePathString(seg[2]).toNodes(),
                fill = SolidColor(Color.Black),
            )
        }
        b.clearGroup()
        b.build()
    }
}

/**
 * Render a Material Symbols Rounded icon by [name] (e.g. `"home"`). Loads the bundle on
 * first use; shows an empty box of the same size until the icon is available. [Icon]
 * applies [tint], so the single-color artwork picks up the theme color.
 */
@Composable
fun SymbolIcon(name: String, modifier: Modifier = Modifier.size(16.dp), tint: Color = Tk.textSecondary) {
    LaunchedEffect(Unit) { Symbols.load() }
    val vector = if (Symbols.loaded) Symbols.vector(name) else null
    if (vector != null) {
        Icon(imageVector = vector, contentDescription = null, modifier = modifier, tint = tint)
    } else {
        Box(modifier) // reserve space until loaded (avoids layout jump)
    }
}
